apiVersion: v1
kind: Pod
metadata:
  name: ese-companion
  labels:
    app: ese-companion
spec:
  containers:
  - name: ese-companion
    image: ese-companion:latest
    env:
      - name: DATABASE_URL
        value: "postgresql://username:password@server:port/database_name?schema=public"
      - name: TOKEN_KEY
        value: "@zoienoinoign!!!!!"
    imagePullPolicy: Always
    ports:
      - name: ui
        containerPort: 3001
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ese-companion
  labels:
    app: ese-companion
spec:
  ports:
  - protocol: TCP
    name: ui
    port: 80
    targetPort: ui
  type: LoadBalancer
  selector:
    app: ese-companion
