CREATE TABLE companion_users (
    id UUID NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_companion_users PRIMARY KEY (id),
    CONSTRAINT uq_companion_users_username UNIQUE (username)
);

CREATE TABLE database_connections (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    db_type VARCHAR(20) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    database_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password TEXT NOT NULL,
    ssl_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    connection_params TEXT,
    health_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    last_health_check TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_database_connections PRIMARY KEY (id),
    CONSTRAINT uq_database_connections_name UNIQUE (name)
);

CREATE TABLE api_keys (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    key_hash VARCHAR(255) NOT NULL,
    key_prefix CHAR(8) NOT NULL,
    scopes TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_api_keys PRIMARY KEY (id),
    CONSTRAINT fk_api_keys_user_id FOREIGN KEY (user_id) REFERENCES companion_users(id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    actor_type VARCHAR(20) NOT NULL,
    actor_id UUID NOT NULL,
    actor_name VARCHAR(255) NOT NULL,
    connection_id UUID,
    connection_name VARCHAR(255),
    domain VARCHAR(20) NOT NULL,
    action VARCHAR(20) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    resource_name VARCHAR(255),
    details TEXT,
    ip_address VARCHAR(45) NOT NULL,
    user_agent TEXT NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);
