{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ese-companion.fullname" . }}
  labels:
    {{- include "ese-companion.labels" . | nindent 4 }}
type: Opaque
data:
  ESE_COMPANION_DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  ESE_COMPANION_JWT_SECRET: {{ .Values.security.jwtSecret | b64enc | quote }}
  ESE_COMPANION_ENCRYPTION_KEY: {{ .Values.security.encryptionKey | b64enc | quote }}
  ESE_COMPANION_ADMIN_USER: {{ .Values.admin.user | b64enc | quote }}
  ESE_COMPANION_ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  ESE_COMPANION_ADMIN_EMAIL: {{ .Values.admin.email | b64enc | quote }}
  {{- if .Values.https.enabled }}
  ESE_COMPANION_HTTPS_PASSWORD: {{ .Values.https.password | b64enc | quote }}
  ESE_COMPANION_HTTPS_PK_PASSWORD: {{ .Values.https.pkPassword | b64enc | quote }}
  {{- end }}
{{- end }}
