/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminConnectionsRouteImport } from './routes/admin/connections'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as ConnectionsConnIdRouteImport } from './routes/connections/$connId'
import { Route as ConnectionsConnIdSettingsRouteImport } from './routes/connections/$connId.settings'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnectionsRoute = AdminConnectionsRouteImport.update({
  id: '/admin/connections',
  path: '/admin/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnIdRoute = ConnectionsConnIdRouteImport.update({
  id: '/connections/$connId',
  path: '/connections/$connId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnIdSettingsRoute = ConnectionsConnIdSettingsRouteImport.update({
  id: '/connections/$connId/settings',
  path: '/connections/$connId/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/connections/$connId': typeof ConnectionsConnIdRoute
  '/connections/$connId/settings': typeof ConnectionsConnIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/connections/$connId': typeof ConnectionsConnIdRoute
  '/connections/$connId/settings': typeof ConnectionsConnIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/connections/$connId': typeof ConnectionsConnIdRoute
  '/connections/$connId/settings': typeof ConnectionsConnIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/settings' | '/admin/audit-logs' | '/admin/connections' | '/admin/users' | '/connections/$connId' | '/connections/$connId/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/settings' | '/admin/audit-logs' | '/admin/connections' | '/admin/users' | '/connections/$connId' | '/connections/$connId/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/connections'
    | '/admin/users'
    | '/connections/$connId'
    | '/connections/$connId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminConnectionsRoute: typeof AdminConnectionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ConnectionsConnIdRoute: typeof ConnectionsConnIdRoute
  ConnectionsConnIdSettingsRoute: typeof ConnectionsConnIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connections': {
      id: '/admin/connections'
      path: '/admin/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof AdminConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connId': {
      id: '/connections/$connId'
      path: '/connections/$connId'
      fullPath: '/connections/$connId'
      preLoaderRoute: typeof ConnectionsConnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connId/settings': {
      id: '/connections/$connId/settings'
      path: '/connections/$connId/settings'
      fullPath: '/connections/$connId/settings'
      preLoaderRoute: typeof ConnectionsConnIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminConnectionsRoute: AdminConnectionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ConnectionsConnIdRoute: ConnectionsConnIdRoute,
  ConnectionsConnIdSettingsRoute: ConnectionsConnIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
